name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Unit Tests
        run: pytest tests/

  train-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
   
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Install Azure CLI
        run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    
      - name: Install Azure ML Extension
        run: az extension add --name ml

      - name: Verify Azure CLI and ML Extension
        run: |
          az --version
          az extension list

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Train Model and Submit Job
        run: |
          az ml job create --file azure_job.yml --resource-group ml --workspace-name har --web --debug

      # - name: Deploy Model
      #   run: |
      #     az ml model deploy -n har-endpoint --model har_model.pkl --overwrite --debug
